### PR TITLE
fix test with default timestamp to give actually the current timestamp

### PR DESCRIPTION
**Pull request by EthanSosivio**
Current default timestamp doesn't give the current timestamp (mine was 6 hours before).  
This fix should give the current timestamp to each insert and fix the tests.

### CODE REVIEW

**Comment by EthanSosivio** [comment]
Hey i see the build still fails but locally all my tests pass.  
How can i see why the build fails?

**Comment by otoolep** [comment]
You click on the "details" link:

https://circleci.com/gh/rqlite/gorqlite/16

```
304331B6-2B0E-CC06-8447-38858E94DD51: leader from store section is [::]:4002
--- FAIL: TestInitCluster (0.00s)
    cluster_test.go:10: trying Open: http://
    cluster_test.go:13: --> FAILED
    cluster_test.go:14: could not determine leader from API status call
```

```
5E99D6C6-89C3-F258-6978-0C95D71554AF: leader from store section is [::]:4002
--- FAIL: TestQueryOne (0.00s)
    query_test.go:16: trying Open
    query_test.go:19: --> FATAL
    query_test.go:20: 
```

**Comment by EthanSosivio** [comment]
Yeah found it, sorry. 
I have updated the version of rqlite image, now it works fine :)

**Comment by otoolep** [comment]
Thanks for your contribution.

**Pull request merged**
