### PR TITLE
Fixes and api.go optimizations

### PR DESCRIPTION
**Pull request by renbou**
Hi! I've introduced lots of fixes and small optimizations, as well as some big ones regarding api.go (http calls):
- fix: proper query parameter parsing for Open(), now timeout query parameter actually works
- fix: timeout for http client is now used for apiPost calls, not only GET
- optimization: strings.Builder instead of bytes.Buffer for string concatenation
- optimization: peer list caching since it changes only during updateClusterInfo()
- optimization: shared http.Client is used for the Connection in order to reuse TCP connections and other resources, like the golang documentation for net/http Client specifies

Also fixed some small example errors in README.
I know that this repo is temporary, however, since it's here to stay at least for now, I think these changes should be included :)

### CODE REVIEW

**Comment by renbou** [comment]
Also I think it's time to move this to go.mod

**Comment by otoolep** [comment]
Thanks for your contribution. I presume there are no breaking changes here, that current users of this code will not need to do anything new to use the library?

**Comment by renbou** [comment]
Yes, there should be no breaking changes

**Review by otoolep — APPROVED** [review]

**Comment by otoolep** [comment]
Thanks for your contribution, this looks like a good clean-up.

**Pull request merged**
